### ISSUE TITLE
Getting stdClass::$orgTable error same as like adminer-4.8.1

### ISSUE THREAD

**Issue by hemroy21** [FrancoisCapon/LoginToASqlite3DatabaseWithoutCredentialsWithAdminer#3] opened 2021-05-21 16:30 UTC
Hello,
I have seen a bug in the dev build for sqlite, which is

![image](https://user-images.githubusercontent.com/83438329/119169521-bb3ecc80-ba7f-11eb-9a33-3489fd6b34cd.png)
`
Warning: Undefined property: stdClass::$orgtable in C:\Bitnami\apachephp\Apache24\htdocs\adminer\adminer-dev.php on line 679
`
This bug is also present in adminer 4.8.1 on line number 1478.

php version 8.0.3
windows 8.1 x64
apache 2.4

dataset was a simple table with three columns and 10 rows.

**Comment by FrancoisCapon** [comment] 2021-05-21 17:31
Hi,

I just compile a new release with adminer 4.8.1 and there is no problem with the [`chinook.db`](https://www.sqlitetutorial.net/sqlite-sample-database/), for example.

```sql
select * from artists
```
But I use PHP 7.4,  can you test with this version of PHP?

**Comment by hemroy21** [comment] 2021-05-22 00:30
> Hi,
> 
> I just compile a new release with adminer 4.8.1 and there is no problem with the [`chinook.db`](https://www.sqlitetutorial.net/sqlite-sample-database/), for example.
> 
> ```sql
> select * from artists
> ```
> 
> But I use PHP 7.4, can you test with this version of PHP?

Yes, just checked, with php older than version 8, adminer has no issues. It may be a version compatibility problem.

Checked with php version 7.0.11 recently, and worked fine.
I will check with the code where it doesn't work with php 8.

**Comment by hemroy21** [comment] 2021-05-22 06:53
Problem solved have found the error, got rid of the error message with a minor hack, checked with php 8.0.3 and php 7.0.11 and works fine with no error.
It was the sqlite driver selection problem, which gets selected when adminer engine detects, which sqlite database gets activated and based on that selection, it selects either sqlite2 or sqlite3 based database driver.

Though the database driver selection is correct but it had to address correctly, specially for sql command execution process at line no 679.

Previously, the process blindly process following variables,
`
$m=$J->fetch_field(); $F=$m->name; $he=$m->orgtable; $ge=$m->orgname; $K[$m->table]=$he;
`
Here $J is the database query result variable that should produce the table meta fields and table details.
Here is the print output of the $m,
`
stdClass Object ( [name] => ID [type] => 1 [charsetnr] => 0 )
`
That result has no fields named orgtable, orgname, table. Hence the error.
But the $m will have those variables if sqlite2 version database driver get selected by the adminer engine.
That is, a check is need to be placed here to check if sqlite (i.e. Sqlite3) or sqlite2 database selected.

Hence I have put the following checking as below.

`
$m=$J->fetch_field();
	$F=$m->name;
	if(isset($_GET['sqlite'])){
		$he=null;$ge=null;
	}else{
		$he=$m->orgtable;
		$ge=$m->orgname;
		$K[$m->table]=$he;
	}
`
Although will check further, with different datasets for validating the problem solution, though request to address this issue with adminer developers as you are one of the important person who solved the sqlite database login problem for many of users like us.
Thanks in advance.
![image_2021-05-22_123031](https://user-images.githubusercontent.com/83438329/119217694-78b9d600-baf9-11eb-94ef-1a4e10fd7245.png)

**Comment by FrancoisCapon** [comment] 2021-05-22 09:49
First thanks for your tests. My conclusion is the same, the issue come from a different behavior between PHP 7.x (Notice) and PHP 8.x (Warning) as you can see:

```php
<?php
highlight_file(__FILE__);
echo '<p>'.PHP_VERSION.'</p>';
$object = (object) array ();
var_dump($object);
var_dump($object->property);

7.4.15

object(stdClass)#1 (0) { }
Notice: Undefined property: stdClass::$property in ... on line 6
NULL

8.0.2

object(stdClass)#1 (0) { }
Warning: Undefined property: stdClass::$property in ... on line 6
NULL
```

Your hack is fine, but in fact the issue is not specific SQLite but to all the adminer's database driver where all the properties of the field object are not set in the [adminer/adminer/include/editing.inc.php](https://github.com/vrana/adminer/blob/1f173e18bdf0be29182e0d67989df56eadea4754/adminer/include/editing.inc.php) file.

If we disable the `sqlite3` extension to force adminer to use `pdo_sqlite` there is a warning on the `type` property.

So, as you suggest, I will propose a patch on the adminer repository to setup all the unknown properties with NULL: 
```php
if (!isset($object->property)) $object->property = NULL;
```

**Comment by FrancoisCapon** [comment] 2021-05-22 11:43
Here is the pull request on the adminer repository: vrana/adminer/pull/429

I close the issue waiting the result of the pull request, meanwhile you can compile a patched version from my fork of adminer:
- https://github.com/FrancoisCapon/adminer

Have a good week-end 😎

**Closed as completed by FrancoisCapon** 2021-05-22 11:43 UTC
Labels: bug

**Comment by hemroy21** [comment] 2021-05-25 17:19
Hello FrancoisCapon, its good that the improvement will surely be added to correct the error along with support to php 8 in the future build, but at the same time developers should improve the ui a little bit, like adding some responsive ui design so that users having small displays don't face problem while using it. I have added some very small improvement to your provided build and added two buttons and one ui animation that helps me to work with adminer nicely as I have to work with adminer by keeping it open on browser. Here is a small video that you may find useful to implement in near future.

https://user-images.githubusercontent.com/83438329/119540421-0f60ee00-bdab-11eb-89aa-34d8e048b6b1.mp4
